### ISSUE TITLE
fail building ecl 21.2.1-1

### ISSUE THREAD

**Issue by veilm** [ehawkvu/kiss-personal#1]
When trying to build your ecl package, I got the following error: http://0x0.st/-407.txt. I think ``mv: can't rename 'libatomic_ops.a': No such file or directory`` is the critical part, but I'm not sure.

Is there something I'm doing wrong?

**Comment by echawk** [comment]
I can confirm this is an issue; It fails to build for me with the same error. I was able to successfully compile ecl when I pushed the package to the repo.

I'll see if I can fix this tonight

**Comment by echawk** [comment]
Just pushed a fix; ecl was able to compile on my machine, let me know if  you are able to compile it

**Comment by veilm** [comment]
ecl compiles fine now, thanks!
