### ISSUE TITLE
Arch-linux-lts need GNUTar and zstd

### ISSUE THREAD

**Issue by GeekOfTheWild** [ehawkvu/kiss-personal#3]
Tested on a pretty much completely fresh install of GKiss, the installation process needs GNUTar (which should be swapped in through the alternatives system), as well as zstd.

**Comment by echawk** [comment]
I'll fix that - did the kernel boot for you? Thank you for testing this btw.

**Comment by GeekOfTheWild** [comment]
No, the kernel did not boot. Additionally, your eudev-git package needs automake to be installed (needs aclocal) and even once that is so, it appears that you need to add "LT_LINT"  to the configure.ac - probably could be done through a patch

**Comment by echawk** [comment]
I forgot that I had eudev-git packaged, I honestly ought to drop it since I haven't used it in ages.

**Comment by GeekOfTheWild** [comment]
Oh okay.
